keboola_fb-ads_extractor_configs_list:
    pattern: /configs
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:get'
    requirements:
        _method: GET
keboola_fb-ads_extractor_configs_add:
    pattern: /configs
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:post'
    requirements:
        _method: POST
keboola_fb-ads_extractor_configs_delete:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:delete'
    requirements:
        _method: DELETE
keboola_fb-ads_extractor_configs_getconfig:
    pattern: '/configs/{id}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:getConfig'
    requirements:
        _method: GET
keboola_fb-ads_extractor_configs_addrow:
    pattern: '/configs/{id}/rows'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_fb-ads_extractor_configs_addrowid:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:addRow'
    requirements:
        _method: POST
keboola_fb-ads_extractor_configs_getrow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:getRow'
    requirements:
        _method: GET
keboola_fb-ads_extractor_configs_deleterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:deleteRow'
    requirements:
        _method: DELETE
keboola_fb-ads_extractor_configs_updaterow:
    pattern: '/configs/{id}/rows/{rowId}'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:addRow'
    requirements:
        _method: PUT
keboola_fb-ads_extractor_configs_addcreds:
    pattern: '/configs/{id}/credentials'
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:Configs:addAttrs'
    requirements:
        _method: POST
keboola_fb-ads_extractor_oauth:
    pattern: /oauth
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:OAuth:getOAuth'
    requirements:
        _method: POST
keboola_fb-ads_extractor_oauth_external:
    pattern: /oauth
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:OAuth:externalAuth'
    requirements:
        _method: GET
keboola_fb-ads_extractor_oauth_callback:
    pattern: /oauth-callback
    defaults:
        _controller: 'KeboolaFacebookAdsExtractorBundle:OAuth:getOAuthCallback'
